name: Restrict Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check_base_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check base branch
        run: |
          base_branch="${{ github.event.pull_request.base.ref }}"
          if [ "$base_branch" != "develop" ]; then
            echo "Pull requests can only be made to master from develop."
            exit 1
          fi
